import {
  MapPin, Package, Route as RouteIcon, Fuel, ShieldCheck, Hexagon, Wrench,
  Video, Cpu, BarChart3, Truck, HardHat, Bus, GraduationCap, Building2,
  Headset, Trash2, Zap, Bell, Gauge, Map, Smartphone, AlertTriangle,
  Star, FileBarChart, History, Activity, LucideIcon,
} from "lucide-react";

export type Item = {
  slug: string;
  title: string;
  short: string;
  description: string;
  icon: LucideIcon;
  benefits: string[];
  features: { title: string; desc: string }[];
  metrics: { value: string; label: string }[];
  faqs?: { q: string; a: string }[];
};

export const solutions: Item[] = [
  {
    slug: "gps-fleet-tracking",
    title: "GPS Fleet Tracking",
    short: "Real-time visibility into every vehicle.",
    description: "Sub-second GPS telemetry with intelligent map clustering, breadcrumb history, and instant location sharing across your operations.",
    icon: MapPin,
    benefits: ["Live 1-second refresh", "99.98% uptime SLA", "Cellular + satellite fallback", "Shareable live links"],
    features: [
      { title: "Live Map", desc: "All vehicles, drivers and assets on one interactive map." },
      { title: "Breadcrumb History", desc: "Replay any trip with second-level precision up to 2 years." },
      { title: "Instant Share", desc: "Send tokenized live-tracking links to customers." },
      { title: "Smart Clustering", desc: "Handle 10,000+ vehicles without slowing down." },
    ],
    metrics: [{ value: "1s", label: "Refresh rate" }, { value: "99.98%", label: "Uptime" }, { value: "2yr", label: "Trip history" }],
  },
  {
    slug: "asset-tracking",
    title: "Asset Tracking",
    short: "Track trailers, containers and equipment.",
    description: "Battery-powered IoT tags with multi-year life. Monitor any asset, anywhere, with geofence-aware alerts.",
    icon: Package,
    benefits: ["5-year battery life", "Indoor & outdoor", "Tamper alerts", "Bulk provisioning"],
    features: [
      { title: "Long-Life Tags", desc: "Multi-year LTE-M tags with motion-based reporting." },
      { title: "Yard Management", desc: "Know what's where, in real time." },
      { title: "Utilization Heatmaps", desc: "Identify under-used assets." },
      { title: "Tamper Alerts", desc: "Instant notification on movement or removal." },
    ],
    metrics: [{ value: "5yr", label: "Battery life" }, { value: "±3m", label: "Accuracy" }, { value: "24/7", label: "Monitoring" }],
  },
  {
    slug: "geofencing",
    title: "Geofencing",
    short: "Smart zones that act on themselves.",
    description: "Draw unlimited geofences and trigger workflows the moment a vehicle enters, dwells or exits.",
    icon: Hexagon,
    benefits: ["Unlimited zones", "Polygon, circle, route fences", "Webhook & SMS triggers", "Dwell-time analytics"],
    features: [
      { title: "Drag-Draw Editor", desc: "Build a fence in seconds on any map." },
      { title: "Smart Triggers", desc: "Auto-dispatch, alert, log or call any API." },
      { title: "Dwell Analytics", desc: "Measure stop time at every site." },
      { title: "Template Libraries", desc: "Re-use fence sets across regions." },
    ],
    metrics: [{ value: "∞", label: "Geofences" }, { value: "<2s", label: "Trigger latency" }, { value: "50+", label: "Integrations" }],
  },
  {
    slug: "driver-monitoring",
    title: "Driver Monitoring",
    short: "Coach drivers, prevent incidents.",
    description: "AI-scored driver behavior with in-cab coaching, gamified leaderboards and incident replay.",
    icon: ShieldCheck,
    benefits: ["Real-time coaching", "Reduced harsh events", "Lower insurance premiums", "Replayable incidents"],
    features: [
      { title: "Behavior Scoring", desc: "Composite score from accel, brake, cornering, speeding." },
      { title: "In-Cab Coaching", desc: "Audio nudges the second a risky event begins." },
      { title: "Leaderboards", desc: "Gamify safety across teams and regions." },
      { title: "Incident Replay", desc: "Pair telemetry with video for full context." },
    ],
    metrics: [{ value: "-58%", label: "Harsh events" }, { value: "-30%", label: "Accidents" }, { value: "+22%", label: "Safety scores" }],
  },
  {
    slug: "fuel-management",
    title: "Fuel Management",
    short: "Cut fuel costs by 15-25%.",
    description: "Detect idling, theft, off-route refueling and inefficient driving with live fuel telemetry.",
    icon: Fuel,
    benefits: ["Idle reduction", "Theft detection", "MPG benchmarking", "Card reconciliation"],
    features: [
      { title: "Idle Reports", desc: "Find the worst offenders in seconds." },
      { title: "Fuel Card Match", desc: "Reconcile every gallon with the right vehicle." },
      { title: "Theft Alerts", desc: "Instant alert on suspicious fuel-level drops." },
      { title: "Eco-Driving", desc: "Rank routes and drivers by MPG." },
    ],
    metrics: [{ value: "-22%", label: "Fuel cost" }, { value: "-41%", label: "Idle time" }, { value: "$1.2k", label: "Saved per vehicle/yr" }],
  },
  {
    slug: "route-optimization",
    title: "Route Optimization",
    short: "AI routing that saves time and miles.",
    description: "Solve thousands of stops in seconds with constraint-aware AI that respects time windows, capacity and skills.",
    icon: RouteIcon,
    benefits: ["Multi-stop optimization", "Time-window aware", "Live re-routing", "Dispatcher console"],
    features: [
      { title: "AI Planner", desc: "10,000 stops in under 30 seconds." },
      { title: "Live Re-Route", desc: "Adapt to traffic, weather, breakdowns." },
      { title: "Driver Mobile App", desc: "Turn-by-turn with proof of delivery." },
      { title: "ETA Engine", desc: "Customer-grade ETAs accurate to ±3 minutes." },
    ],
    metrics: [{ value: "-31%", label: "Miles driven" }, { value: "+27%", label: "Stops/day" }, { value: "±3m", label: "ETA accuracy" }],
  },
  {
    slug: "maintenance-management",
    title: "Maintenance Management",
    short: "Predict failures, schedule smarter.",
    description: "Fault-code intelligence, mileage-based reminders and a full digital service history per vehicle.",
    icon: Wrench,
    benefits: ["Fault-code intelligence", "Preventive scheduling", "Digital service log", "Vendor workflow"],
    features: [
      { title: "DTC Decoder", desc: "Plain-English explanations of every fault code." },
      { title: "PM Scheduler", desc: "By mileage, engine hours or date." },
      { title: "Service History", desc: "Searchable, exportable, audit-ready." },
      { title: "Vendor Portal", desc: "Quote, approve and pay from one place." },
    ],
    metrics: [{ value: "-44%", label: "Downtime" }, { value: "-19%", label: "Repair costs" }, { value: "100%", label: "Compliance" }],
  },
  {
    slug: "video-telematics",
    title: "Video Telematics",
    short: "AI dashcams with road + driver view.",
    description: "Dual-facing HD cameras with on-device AI to detect distraction, drowsiness and collisions.",
    icon: Video,
    benefits: ["Edge AI detection", "Cloud upload on event", "Driver-facing privacy controls", "Insurance-grade evidence"],
    features: [
      { title: "Edge AI", desc: "Detect events on-device, upload only what matters." },
      { title: "DMS", desc: "Driver Monitoring System with fatigue + phone-use." },
      { title: "Auto-Upload", desc: "Event clips arrive in the cloud within seconds." },
      { title: "Exoneration", desc: "Defend drivers with HD footage in disputes." },
    ],
    metrics: [{ value: "1080p", label: "HD video" }, { value: "<10s", label: "Event upload" }, { value: "-62%", label: "Claims cost" }],
  },
  {
    slug: "vehicle-diagnostics",
    title: "Vehicle Diagnostics",
    short: "OEM data, decoded and actionable.",
    description: "Read engine, battery, EV state of charge and 200+ parameters across mixed brand fleets.",
    icon: Cpu,
    benefits: ["Multi-OEM support", "EV + ICE", "Battery health", "Predictive alerts"],
    features: [
      { title: "Mixed-Fleet", desc: "One pane of glass for ICE, hybrid and EV." },
      { title: "EV Monitoring", desc: "State of charge, range, charging sessions." },
      { title: "Battery Health", desc: "Predict 12V battery failure before it strands." },
      { title: "OEM API", desc: "Connect Ford, GM, Stellantis and more, no hardware required." },
    ],
    metrics: [{ value: "200+", label: "Parameters" }, { value: "40+", label: "OEMs" }, { value: "EV+ICE", label: "Coverage" }],
  },
  {
    slug: "reports-analytics",
    title: "Reports & Analytics",
    short: "Insights that move the business.",
    description: "Drag-and-drop dashboards, scheduled reports and a warehouse-ready BI layer.",
    icon: BarChart3,
    benefits: ["No-code dashboards", "Scheduled exports", "Warehouse sync", "Role-based views"],
    features: [
      { title: "Dashboard Builder", desc: "Build any view in minutes." },
      { title: "Scheduled Reports", desc: "PDF, CSV or API delivery." },
      { title: "Warehouse Sync", desc: "Native Snowflake, BigQuery, Redshift." },
      { title: "Role-Based", desc: "Granular access by team, region or role." },
    ],
    metrics: [{ value: "120+", label: "Pre-built reports" }, { value: "BI", label: "Ready" }, { value: "SOC2", label: "Compliant" }],
  },
];

export const industries: Item[] = [
  { slug: "logistics", title: "Logistics & Distribution", short: "Move freight smarter.", description: "From first mile to last, mylr.ai powers high-volume distribution with real-time visibility and route intelligence.",
    icon: Truck,
    benefits: ["Real-time ETAs", "Yard management", "Driver compliance", "Customer portals"],
    features: [{ title: "Dispatch Suite", desc: "Plan, assign and track in one console." }, { title: "ELD/HOS", desc: "Built-in compliance and audit logs." }, { title: "Customer Visibility", desc: "Branded tracking links." }, { title: "Proof of Delivery", desc: "Photo + signature capture." }],
    metrics: [{ value: "-28%", label: "On-time delays" }, { value: "+19%", label: "Loads/week" }, { value: "100%", label: "ELD compliant" }],
  },
  { slug: "construction", title: "Construction", short: "Equipment, crews and sites in sync.",
    description: "Track heavy equipment and crew vehicles across job sites. Reduce theft, track utilization and improve safety.", icon: HardHat,
    benefits: ["Asset utilization", "Theft prevention", "Site geofencing", "Operator safety"],
    features: [{ title: "Equipment Tracking", desc: "Powered and non-powered assets." }, { title: "Site Fences", desc: "Auto-clock-in by location." }, { title: "Utilization", desc: "Engine hours and idle ratios." }, { title: "Operator ID", desc: "RFID-linked operator data." }],
    metrics: [{ value: "+34%", label: "Utilization" }, { value: "-71%", label: "Theft" }, { value: "-22%", label: "Idle hours" }],
  },
  { slug: "public-transport", title: "Public Transport", short: "Reliable transit, happier riders.",
    description: "Live ETAs, route adherence and headway management for buses, trams and regional transit.", icon: Bus,
    benefits: ["Rider apps", "Headway control", "Schedule adherence", "Accessibility data"],
    features: [{ title: "Rider ETAs", desc: "Real-time arrival predictions." }, { title: "Headway Mgmt", desc: "Keep buses evenly spaced." }, { title: "AVL", desc: "Automatic Vehicle Location." }, { title: "Open Data", desc: "GTFS-RT feeds out of the box." }],
    metrics: [{ value: "+18%", label: "On-time" }, { value: "-12%", label: "Bunching" }, { value: "GTFS-RT", label: "Native" }],
  },
  { slug: "school-transportation", title: "School Transportation", short: "Safety first, parents informed.",
    description: "Specialized tools for school bus fleets: student ridership, parent apps and stop-arm safety.", icon: GraduationCap,
    benefits: ["Parent transparency", "Student ridership", "Stop-arm cameras", "Driver coaching"],
    features: [{ title: "Parent App", desc: "Where's the bus, in real time." }, { title: "Ridership", desc: "Tap-on/tap-off RFID." }, { title: "Stop-Arm Cam", desc: "Capture passing violations." }, { title: "Safety Scores", desc: "Coach drivers around students." }],
    metrics: [{ value: "200k+", label: "Students" }, { value: "-44%", label: "Incidents" }, { value: "98%", label: "Parent NPS" }],
  },
  { slug: "government", title: "Government & Municipal", short: "Public works, accountable and efficient.",
    description: "Plows, sweepers, inspectors and patrol — all visible, all reportable.", icon: Building2,
    benefits: ["FOIA-ready reports", "Service verification", "Cost-per-mile", "Open APIs"],
    features: [{ title: "Citizen Maps", desc: "Show service routes publicly." }, { title: "Audit Logs", desc: "Tamper-evident records." }, { title: "Cost Allocation", desc: "By department and project." }, { title: "Procurement Friendly", desc: "GSA-compatible." }],
    metrics: [{ value: "GovCloud", label: "Hosted" }, { value: "FedRAMP", label: "In progress" }, { value: "$M", label: "Saved annually" }],
  },
  { slug: "field-services", title: "Field Services", short: "Right tech, right time, right place.",
    description: "Schedule, dispatch and verify field work with live ETAs and proof of service.", icon: Headset,
    benefits: ["Live ETAs to customers", "Skill-based dispatch", "Proof of service", "Parts inventory"],
    features: [{ title: "Smart Dispatch", desc: "Match skills to jobs automatically." }, { title: "Customer ETAs", desc: "Branded SMS notifications." }, { title: "PoS", desc: "Photos, signatures, forms." }, { title: "Parts Tracking", desc: "Trunk stock visibility." }],
    metrics: [{ value: "+24%", label: "Jobs/day" }, { value: "-19%", label: "Drive time" }, { value: "97%", label: "FTFR" }],
  },
  { slug: "waste-management", title: "Waste Management", short: "Smarter routes, cleaner cities.",
    description: "Optimize pickup routes, verify service and reduce missed stops with on-truck cameras.", icon: Trash2,
    benefits: ["Route adherence", "RFID bin verification", "Camera proof", "Citizen apps"],
    features: [{ title: "Route Adherence", desc: "Visualize completion in real time." }, { title: "Bin RFID", desc: "Verify every lift." }, { title: "Service Cameras", desc: "Photo evidence of pickups." }, { title: "Resident Portal", desc: "Schedule and report missed stops." }],
    metrics: [{ value: "-26%", label: "Missed stops" }, { value: "+15%", label: "Route efficiency" }, { value: "100%", label: "Verified lifts" }],
  },
  { slug: "utilities", title: "Utilities & Energy", short: "Crews, trucks and outages in one view.",
    description: "Coordinate crews and respond to outages faster with integrated GIS and OMS workflows.", icon: Zap,
    benefits: ["Outage response", "Crew safety", "GIS integration", "Storm mode"],
    features: [{ title: "Storm Mode", desc: "Scale to 10x crews instantly." }, { title: "GIS Sync", desc: "ArcGIS native overlays." }, { title: "Lone Worker", desc: "Check-in safety workflows." }, { title: "OMS Hooks", desc: "Trigger from outage events." }],
    metrics: [{ value: "-37%", label: "Response time" }, { value: "GIS", label: "Native" }, { value: "24/7", label: "Crew safety" }],
  },
];

export const features: Item[] = [
  { slug: "live-tracking", title: "Live Tracking", short: "1-second telemetry, anywhere.", description: "True real-time updates with global cellular coverage and satellite fallback.", icon: MapPin,
    benefits: ["1s refresh", "Global coverage", "Live share links", "Multi-map providers"],
    features: [{ title: "Multi-Map", desc: "Mapbox, Google, HERE." }, { title: "Live Share", desc: "Tokenized public links." }, { title: "Replay", desc: "Trip replay at any speed." }, { title: "Clustering", desc: "Smooth at 10k+ vehicles." }],
    metrics: [{ value: "1s", label: "Refresh" }, { value: "Global", label: "Coverage" }] },
  { slug: "real-time-alerts", title: "Real-Time Alerts", short: "Notify the right person, instantly.", description: "Route alerts by role, region or rule. SMS, email, push, webhook.", icon: Bell,
    benefits: ["Multi-channel", "Smart escalation", "Quiet hours", "Acknowledgement"],
    features: [{ title: "Channels", desc: "SMS, push, email, webhook, Slack." }, { title: "Escalation", desc: "If unacknowledged in N minutes." }, { title: "Quiet Hours", desc: "Honor schedules per recipient." }, { title: "Templates", desc: "Branded message templates." }],
    metrics: [{ value: "<5s", label: "Delivery" }, { value: "6", label: "Channels" }] },
  { slug: "geofence-management", title: "Geofence Management", short: "Smart zones with smart actions.", description: "Build, organize and trigger thousands of geofences with zero code.", icon: Hexagon,
    benefits: ["Bulk import", "Templates", "Triggers", "Analytics"],
    features: [{ title: "Bulk Import", desc: "CSV, KML, Shapefile." }, { title: "Templates", desc: "Re-use across regions." }, { title: "Actions", desc: "Webhook or notify." }, { title: "Dwell", desc: "Time-in-zone metrics." }],
    metrics: [{ value: "∞", label: "Zones" }, { value: "<2s", label: "Triggers" }] },
  { slug: "fleet-dashboard", title: "Fleet Dashboard", short: "Mission control for your fleet.", description: "A configurable command center with widgets for every role.", icon: Gauge,
    benefits: ["No-code widgets", "Per-role views", "Big-screen mode", "Realtime KPIs"],
    features: [{ title: "Widgets", desc: "30+ widget types." }, { title: "Big-Screen", desc: "NOC-grade displays." }, { title: "Per-Role", desc: "Dispatcher, manager, exec." }, { title: "Embed", desc: "Drop into any portal." }],
    metrics: [{ value: "30+", label: "Widgets" }, { value: "1s", label: "Updates" }] },
  { slug: "mobile-app", title: "Mobile App", short: "iOS + Android, for managers and drivers.", description: "Beautiful native apps for drivers, managers and executives.", icon: Smartphone,
    benefits: ["Driver workflows", "Manager approvals", "Offline mode", "Biometric login"],
    features: [{ title: "Driver", desc: "Turn-by-turn, DVIR, messaging." }, { title: "Manager", desc: "Approve, dispatch, alert." }, { title: "Offline", desc: "Capture jobs without signal." }, { title: "Biometric", desc: "Secure by default." }],
    metrics: [{ value: "iOS", label: "Native" }, { value: "Android", label: "Native" }] },
  { slug: "maintenance-alerts", title: "Maintenance Alerts", short: "Never miss a service window.", description: "Fault-code, mileage and time-based alerts with vendor workflows.", icon: AlertTriangle,
    benefits: ["DTC decoded", "Mileage/time", "Vendor flow", "Audit log"],
    features: [{ title: "DTC", desc: "Plain-English faults." }, { title: "PM", desc: "Configurable cadences." }, { title: "Vendors", desc: "Quote and approve." }, { title: "History", desc: "Full audit log." }],
    metrics: [{ value: "-44%", label: "Downtime" }] },
  { slug: "driver-scorecards", title: "Driver Scorecards", short: "Coaching that actually works.", description: "Composite scores with personalized coaching plans.", icon: Star,
    benefits: ["Composite scoring", "Coaching plans", "Gamification", "Trends"],
    features: [{ title: "Scoring", desc: "Accel, brake, corner, speed." }, { title: "Coaching", desc: "Auto-assign actions." }, { title: "Leaderboards", desc: "Per team or region." }, { title: "Trends", desc: "Track improvement." }],
    metrics: [{ value: "-58%", label: "Harsh events" }] },
  { slug: "fuel-insights", title: "Fuel Insights", short: "Find every wasted gallon.", description: "Fuel card reconciliation, idle reports and theft detection.", icon: Fuel,
    benefits: ["Card match", "Idle", "Theft", "MPG"],
    features: [{ title: "Card Match", desc: "Reconcile every transaction." }, { title: "Idle", desc: "Top offenders, instantly." }, { title: "Theft", desc: "Alerts on drops." }, { title: "MPG", desc: "Per vehicle and driver." }],
    metrics: [{ value: "-22%", label: "Fuel cost" }] },
  { slug: "trip-history", title: "Trip History", short: "Replay any trip, any time.", description: "Two years of trip-level history with stop, idle and event detail.", icon: History,
    benefits: ["2-year retention", "Stops + idles", "Events", "Export"],
    features: [{ title: "Retention", desc: "Up to 2 years standard." }, { title: "Replay", desc: "Variable speed playback." }, { title: "Stops", desc: "Auto-detected with duration." }, { title: "Export", desc: "CSV, GeoJSON, API." }],
    metrics: [{ value: "2yr", label: "Retention" }] },
  { slug: "reporting", title: "Reporting", short: "Reports that arrive in inboxes.", description: "120+ pre-built reports and a no-code builder for the rest.", icon: FileBarChart,
    benefits: ["120+ reports", "Custom builder", "Scheduled delivery", "BI ready"],
    features: [{ title: "Library", desc: "120+ pre-built." }, { title: "Builder", desc: "No-code custom." }, { title: "Schedule", desc: "Email, S3, API." }, { title: "BI Sync", desc: "Snowflake, BigQuery." }],
    metrics: [{ value: "120+", label: "Reports" }] },
];

export type Post = { slug: string; title: string; excerpt: string; category: string; readTime: string; date: string; author: string; body: string[] };
export const posts: Post[] = [
  { slug: "ai-fleet-2026", title: "The State of AI in Fleet Management 2026", excerpt: "How edge AI, predictive maintenance and route intelligence are reshaping logistics economics.", category: "AI & ML", readTime: "9 min", date: "Jun 4, 2026", author: "Dr. Maya Chen",
    body: [
      "Fleet operators are no longer asking whether AI belongs in their operations — they're asking how fast they can deploy it without disrupting the business.",
      "Edge AI in dashcams now detects distracted driving in under 200 milliseconds. Predictive maintenance models flag battery failures days before they strand a driver. Route optimization that once took analysts hours now runs in seconds on every dispatch.",
      "The economics are striking. Fleets adopting AI-driven workflows are seeing 22% reductions in fuel cost, 44% reductions in unplanned downtime, and 58% fewer harsh-driving events. The compounding effect, once an organization standardizes on a single intelligence layer, redefines unit economics for the entire operation.",
      "What separates winners from laggards is data discipline. The fleets seeing the biggest gains treat telemetry as a strategic asset — owned, governed, and connected to every downstream system from finance to safety to customer experience.",
    ],
  },
  { slug: "reduce-fuel-costs", title: "5 Proven Ways to Cut Fuel Costs by 20%", excerpt: "Idle reduction, route optimization and driver coaching deliver compounding savings.", category: "Operations", readTime: "6 min", date: "May 22, 2026", author: "Jordan Park",
    body: ["Fuel is the second-largest cost line for most fleets. Here are the five tactics with the largest, most repeatable impact.", "1. Eliminate idling. Most fleets idle 30-40% of engine hours. Live alerts and scorecards can halve that within 90 days.", "2. Optimize routes daily. Static routes leak miles. AI optimization replans against live conditions and shaves 15-25% off total distance.", "3. Coach drivers in real time. In-cab audio nudges work better than weekly emails — the right feedback, the moment of the event.", "4. Reconcile every fuel-card transaction. Mismatches between cards and vehicles surface theft and misuse instantly.", "5. Benchmark MPG by route, driver and vehicle to find the outliers worth fixing first."] },
  { slug: "ev-fleet-transition", title: "Planning Your EV Fleet Transition", excerpt: "A pragmatic playbook for shifting from ICE to electric without disrupting operations.", category: "Sustainability", readTime: "11 min", date: "May 8, 2026", author: "Priya Natarajan",
    body: ["The path to an electric fleet is paved with data. Telematics tells you which routes are EV-ready today, which depots need chargers, and how to sequence the transition over 3-5 years.", "Start with a route suitability analysis. Use 90 days of trip history to identify duty cycles that fit current EV range with margin.", "Next, model charging needs at each depot. Telematics + dwell-time analytics gives you a defensible charging strategy without overbuilding.", "Finally, instrument every EV from day one. State of charge, battery health and charging session data are critical to TCO realization."] },
  { slug: "driver-safety", title: "How Real-Time Coaching Reduces Accidents by 40%", excerpt: "In-cab feedback transforms driving behavior in weeks, not quarters.", category: "Safety", readTime: "7 min", date: "Apr 19, 2026", author: "Marcus Reed",
    body: ["Driver safety is the single largest insurable risk for a fleet. Real-time, in-cab coaching changes the unit economics of that risk.", "Traditional safety programs rely on after-the-fact reviews. By the time a manager sees a harsh-event report, the driver has reinforced the behavior 50 more times.", "In-cab coaching closes the loop in seconds. The driver hears the nudge the instant they cross the threshold. Within 12 weeks, harsh events typically drop 50-60% and accident rates follow within two quarters."] },
  { slug: "geofencing-101", title: "Geofencing 101: Beyond Simple Zones", excerpt: "Modern geofences are programmable workflows that act on themselves.", category: "Platform", readTime: "5 min", date: "Apr 3, 2026", author: "Elena Volkov",
    body: ["A geofence used to be a circle on a map that triggered a notification. Today it's a programmable workflow.", "Modern fences support polygons, route corridors, dwell-time conditions and chained actions. The result is fewer alerts and more automation."] },
  { slug: "telematics-roi", title: "Building the ROI Case for Telematics", excerpt: "A CFO-grade model for justifying a platform investment.", category: "Business", readTime: "8 min", date: "Mar 22, 2026", author: "Sarah Kim",
    body: ["Telematics ROI lives in three buckets: cost takeout, productivity, and risk reduction. Quantify each with conservative assumptions and a 3-year horizon.", "Most fleets see payback inside 7 months, with year-3 ROI between 4x and 9x."] },
];

export type CaseStudy = { slug: string; client: string; industry: string; logo: string; headline: string; summary: string; challenge: string; solution: string; results: { value: string; label: string }[] };
export const cases: CaseStudy[] = [
  { slug: "northwind-logistics", client: "Northwind Logistics", industry: "Logistics", logo: "NORTHWIND", headline: "Northwind cut delivery times by 31% in 6 months", summary: "How a 4,200-vehicle distribution fleet rebuilt its dispatch operations around live telemetry and AI routing.",
    challenge: "Northwind operated 18 distribution centers with siloed dispatch tools and no shared view of in-transit assets. ETAs were unreliable, harsh-event rates were rising, and the executive team had no single source of truth.",
    solution: "mylr.ai replaced four legacy platforms with one. Live telemetry, AI route optimization, driver coaching and a unified executive dashboard rolled out across all 18 DCs in 90 days.",
    results: [{ value: "-31%", label: "Delivery time" }, { value: "+22%", label: "Stops per day" }, { value: "-58%", label: "Harsh events" }, { value: "$4.2M", label: "Annual savings" }] },
  { slug: "buildwell-construction", client: "Buildwell Construction", industry: "Construction", logo: "BUILDWELL", headline: "Buildwell eliminated $1.8M in equipment theft", summary: "Multi-state contractor uses geofencing and asset tags to protect 6,400 pieces of equipment.",
    challenge: "Buildwell lost millions annually to equipment theft and idle drift across active job sites. Manual checks were inconsistent and after-the-fact.", 
    solution: "Asset tags on every piece of equipment, geofences on every site, instant alerts on after-hours movement, and automated utilization reports for every project manager.",
    results: [{ value: "-71%", label: "Theft loss" }, { value: "+34%", label: "Utilization" }, { value: "$1.8M", label: "Recovered" }, { value: "6,400", label: "Assets tagged" }] },
  { slug: "urbanmove-transit", client: "UrbanMove Transit", industry: "Public Transport", logo: "URBANMOVE", headline: "UrbanMove lifted on-time performance to 94%", summary: "Regional transit agency modernized AVL and rider experience with one platform.",
    challenge: "Aging AVL infrastructure, no real-time rider information, and bunching during peak hours.",
    solution: "mylr.ai replaced legacy AVL with modern telematics, rolled out a rider app, and gave dispatchers a headway-management console.",
    results: [{ value: "94%", label: "On-time" }, { value: "-12%", label: "Bunching" }, { value: "+47%", label: "Rider app NPS" }, { value: "320", label: "Vehicles" }] },
  { slug: "schoolnet-transportation", client: "SchoolNet Transportation", industry: "School Transport", logo: "SCHOOL·NET", headline: "SchoolNet protects 180,000 student rides per day", summary: "Nation's largest pupil-transport contractor unified safety, ridership and parent communications.",
    challenge: "Disparate systems for routing, ridership tracking, parent comms, and stop-arm enforcement.",
    solution: "One platform for routing, ridership RFID, stop-arm cameras and the parent app — deployed to 4,800 buses.",
    results: [{ value: "180k", label: "Daily riders" }, { value: "-44%", label: "Incidents" }, { value: "98%", label: "Parent NPS" }, { value: "4,800", label: "Buses" }] },
  { slug: "rapid-field-services", client: "Rapid Field Services", industry: "Field Services", logo: "RAPID·SERV", headline: "Rapid increased jobs-per-tech 24% with smart dispatch", summary: "HVAC service company rebuilt its dispatch and customer experience.",
    challenge: "Manual dispatch, long customer arrival windows and low first-time fix rates.",
    solution: "Skill-based dispatch, live customer ETAs, mobile parts inventory and on-vehicle telematics.",
    results: [{ value: "+24%", label: "Jobs/day" }, { value: "97%", label: "FTFR" }, { value: "-19%", label: "Drive time" }, { value: "+38", label: "NPS" }] },
  { slug: "govfleet-municipal", client: "Gov·Fleet Metro", industry: "Government", logo: "GOV·FLEET", headline: "Metro saved $6M and proved every plow route", summary: "Large municipality unified public-works fleet visibility with FOIA-ready reporting.",
    challenge: "Citizen complaints about missed services, no defensible record of work performed, and rising operational costs.",
    solution: "Telematics on every plow, sweeper and inspector vehicle, with a public route map and tamper-evident audit logs.",
    results: [{ value: "$6M", label: "Saved" }, { value: "100%", label: "Routes verified" }, { value: "-58%", label: "Complaints" }, { value: "1,200", label: "Vehicles" }] },
];

export const stats = [
  { value: "500K+", label: "Vehicles tracked" },
  { value: "120+", label: "Countries served" },
  { value: "12B+", label: "Data points/day" },
  { value: "99.98%", label: "Platform uptime" },
];
